-- MySQL Script generated by MySQL Workbench
-- Sun May  5 11:08:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stu_form
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stu_form
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stu_form` DEFAULT CHARACTER SET utf8 ;
USE `stu_form` ;

-- -----------------------------------------------------
-- Table `stu_form`.`stu_infor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stu_form`.`stu_infor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prefixname` VARCHAR(20) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `stampdate` DATE NOT NULL,
  `id_stu` VARCHAR(8) NOT NULL,
  `code` INT(1) NOT NULL,
  `fly` INT(1) NOT NULL,
  `shoot` INT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
